samples: "/beegfs-storage/data/test_data/gms560/samples.tsv"
units: "/beegfs-storage/data/test_data/gms560/units.tsv"
resources: "/beegfs-storage/data/test_data/gms560/resources.yaml"

default_container: "docker://hydragenetics/common:0.0.1"

trimmer_software: "fastp"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"
