$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  trimmer_software:
    type: string
  samples:
    type: string
  units:
    type: string
  containers:
    type: object
    properties:
      common:
        type: string
    required:
      - common
  fastp_pe:
    type: object
    properties:
      benchmark_repeats:
        type: string
        description: set number of times benchmark should be repeated for fastp_pe
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded to fastp
  merged:
    type: object
    properties:
      benchmark_repeats:
        type: string
        description: set number of times benchmark should be repeated for fastp_pe
      container:
        type: string
        description: name or path to docker/singularity container
  required:
    - samples
    - units
    - containers
