samples: "samples.tsv"
units: "units.tsv"
resources: "resources.yaml"

default_container: "docker://hydragenetics/common:0.0.1"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

trimmer_software: None
